// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjOaQh3KOIvppmJLhPZvvVIkDR6lXmKgA',
    appId: '1:503905000246:web:3d78abdc79b24ecdea7197',
    messagingSenderId: '503905000246',
    projectId: 'untense',
    authDomain: 'untense.firebaseapp.com',
    storageBucket: 'untense.firebasestorage.app',
    measurementId: 'G-58HMC02C4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHeqvel_BlHSl1DmsA8P5-OoBj2U_9PY0',
    appId: '1:503905000246:android:1687d3a49c0a1f6dea7197',
    messagingSenderId: '503905000246',
    projectId: 'untense',
    storageBucket: 'untense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDcqjPU8-pEcaXIdQ6Pst9l9vWbFCusA8',
    appId: '1:503905000246:ios:d7db61a0c6b64173ea7197',
    messagingSenderId: '503905000246',
    projectId: 'untense',
    storageBucket: 'untense.firebasestorage.app',
    iosBundleId: 'com.example.untenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDcqjPU8-pEcaXIdQ6Pst9l9vWbFCusA8',
    appId: '1:503905000246:ios:d7db61a0c6b64173ea7197',
    messagingSenderId: '503905000246',
    projectId: 'untense',
    storageBucket: 'untense.firebasestorage.app',
    iosBundleId: 'com.example.untenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjOaQh3KOIvppmJLhPZvvVIkDR6lXmKgA',
    appId: '1:503905000246:web:c543112a3120cf91ea7197',
    messagingSenderId: '503905000246',
    projectId: 'untense',
    authDomain: 'untense.firebaseapp.com',
    storageBucket: 'untense.firebasestorage.app',
    measurementId: 'G-03M80BN3ME',
  );
}
